# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-14 11:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('english_title', models.CharField(max_length=200)),
                ('japanese_title', models.CharField(max_length=200)),
                ('year', models.IntegerField()),
                ('imdb_link', models.TextField()),
                ('tmd_link', models.TextField()),
                ('image_url', models.TextField()),
            ],
        ),
    ]
